import { useMemo } from "react";
import {
  buildChatSessionContext,
  type BuildChatSessionContextInput,
} from "../../../application/chat/session-context";

export function useChatSessionContext(input: BuildChatSessionContextInput) {
  const {
    activeCompany,
    activeConversationState,
    activeAgentRuntime,
    activeRequirementRoom,
    activeRoomBindings,
    activeRoomRecords,
    activeRoundRecords,
    archiveHistoryNotice,
    archiveId,
    companySessionSnapshots,
    connected,
    currentTime,
    effectiveGroupSessionKey,
    groupMembers,
    groupTitle,
    groupWorkItemId,
    historyAgentId,
    isArchiveView,
    isGenerating,
    isGroup,
    loading,
    messages,
    recentAgentSessions,
    recentArchivedRounds,
    routeRoomId,
    sessionKey,
    streamText,
    targetAgentId,
  } = input;

  return useMemo(
    () =>
      buildChatSessionContext({
        activeCompany,
        activeConversationState,
        activeAgentRuntime,
        activeRequirementRoom,
        activeRoomBindings,
        activeRoomRecords,
        activeRoundRecords,
        archiveHistoryNotice,
        archiveId,
        companySessionSnapshots,
        connected,
        currentTime,
        effectiveGroupSessionKey,
        groupMembers,
        groupTitle,
        groupWorkItemId,
        historyAgentId,
        isArchiveView,
        isGenerating,
        isGroup,
        loading,
        messages,
        recentAgentSessions,
        recentArchivedRounds,
        routeRoomId,
        sessionKey,
        streamText,
        targetAgentId,
      }),
    [
      activeCompany,
      activeConversationState,
      activeAgentRuntime,
      activeRequirementRoom,
      activeRoomBindings,
      activeRoomRecords,
      activeRoundRecords,
      archiveHistoryNotice,
      archiveId,
      companySessionSnapshots,
      connected,
      currentTime,
      effectiveGroupSessionKey,
      groupMembers,
      groupTitle,
      groupWorkItemId,
      historyAgentId,
      isArchiveView,
      isGenerating,
      isGroup,
      loading,
      messages,
      recentAgentSessions,
      recentArchivedRounds,
      routeRoomId,
      sessionKey,
      streamText,
      targetAgentId,
    ],
  );
}
