import { describe, expect, it } from "vitest";
import { runtimeStateFromAuthorityRuntimeSnapshot } from "./runtime-snapshot";
import type { AuthorityCompanyRuntimeSnapshot } from "./contract";

describe("runtimeStateFromAuthorityRuntimeSnapshot", () => {
  it("self-heals recursively wrapped strategic identities from authority runtime snapshots", () => {
    const snapshot: AuthorityCompanyRuntimeSnapshot = {
      companyId: "company-1",
      activeRoomRecords: [
        {
          id: "workitem:topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          companyId: "company-1",
          workItemId: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          sessionKey: "room:workitem:topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          title: "从头开始搭建 AI 小说创作团队",
          topicKey: "aggregate:topic:aggregate:topic:mission:alpha@1000",
          memberIds: ["co-ceo", "co-cto"],
          memberActorIds: ["co-ceo", "co-cto"],
          ownerAgentId: "co-ceo",
          ownerActorId: "co-ceo",
          status: "active",
          headline: "从头开始搭建 AI 小说创作团队",
          progress: "等待 CTO 方案",
          transcript: [],
          createdAt: 1_000,
          updatedAt: 2_000,
        },
      ],
      activeMissionRecords: [
        {
          id: "topic:aggregate:topic:mission:alpha@1000",
          sessionKey: "agent:co-ceo:main",
          topicKey: "aggregate:topic:mission:alpha@1000",
          roomId: "workitem:topic:aggregate:topic:mission:alpha@1000",
          startedAt: 1_000,
          promotionState: "active_requirement",
          promotionReason: null,
          lifecyclePhase: "active_requirement",
          stageGateStatus: "confirmed",
          title: "从头开始搭建 AI 小说创作团队",
          statusLabel: "进行中",
          progressLabel: "等待 CTO 方案",
          ownerAgentId: "co-ceo",
          ownerLabel: "CEO",
          currentStepLabel: "CEO 发起主线",
          nextAgentId: "co-cto",
          nextLabel: "CTO",
          summary: "从头开始搭建 AI 小说创作团队。",
          guidance: "让 CTO 和 COO 分别给出方案。",
          completed: false,
          updatedAt: 2_000,
          planSteps: [],
        },
      ],
      activeConversationStates: [
        {
          companyId: "company-1",
          conversationId: "agent:co-ceo:main",
          currentWorkKey: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000",
          currentWorkItemId: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          currentRoundId: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          draftRequirement: null,
          updatedAt: 2_000,
        },
      ],
      activeWorkItems: [
        {
          id: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          workKey: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          kind: "strategic",
          roundId: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          companyId: "company-1",
          sessionKey: "agent:co-ceo:main",
          topicKey: "aggregate:topic:aggregate:topic:mission:alpha@1000",
          sourceActorId: "co-ceo",
          sourceActorLabel: "CEO",
          sourceSessionKey: "agent:co-ceo:main",
          sourceConversationId: "agent:co-ceo:main",
          providerId: null,
          title: "从头开始搭建 AI 小说创作团队",
          goal: "把组织、规范、工具和流程从头搭起来。",
          headline: "从头开始搭建 AI 小说创作团队",
          displayStage: "CEO 发起主线",
          displaySummary: "主线正在推进。",
          displayOwnerLabel: "CEO",
          displayNextAction: "让 CTO 和 COO 给方案。",
          status: "active",
          lifecyclePhase: "active_requirement",
          stageGateStatus: "confirmed",
          stageLabel: "CEO 发起主线",
          ownerActorId: "co-ceo",
          ownerLabel: "CEO",
          batonActorId: "co-cto",
          batonLabel: "CTO",
          roomId: "workitem:topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          artifactIds: [],
          dispatchIds: [],
          startedAt: 1_000,
          updatedAt: 2_000,
          completedAt: null,
          summary: "主线正在推进。",
          nextAction: "让 CTO 和 COO 给方案。",
          steps: [],
        },
      ],
      activeRequirementAggregates: [
        {
          id: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          companyId: "company-1",
          topicKey: null,
          kind: "strategic",
          primary: true,
          workItemId: null,
          roomId: "workitem:topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          ownerActorId: "co-ceo",
          ownerLabel: "CEO",
          lifecyclePhase: "active_requirement",
          stageGateStatus: "confirmed",
          stage: "CEO 发起主线",
          summary: "从头开始搭建 AI 小说创作团队。",
          nextAction: "让 CTO 和 COO 给方案。",
          memberIds: ["co-ceo", "co-cto"],
          sourceConversationId: "agent:co-ceo:main",
          startedAt: 1_000,
          updatedAt: 2_000,
          revision: 1,
          lastEvidenceAt: null,
          status: "active",
          acceptanceStatus: "not_requested",
          acceptanceNote: null,
        },
      ],
      activeRequirementEvidence: [
        {
          id: "evt-1",
          companyId: "company-1",
          aggregateId: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
          source: "company-event",
          sessionKey: "agent:co-ceo:main",
          actorId: "system:requirement-aggregate",
          eventType: "requirement_promoted",
          timestamp: 2_500,
          payload: {
            workItemId: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
            roomId: "workitem:topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
            topicKey: "aggregate:topic:aggregate:topic:mission:alpha@1000",
          },
          applied: true,
        },
      ],
      primaryRequirementId: "topic:aggregate:topic:aggregate:topic:mission:alpha@1000@2000",
      activeRoundRecords: [],
      activeArtifacts: [],
      activeDispatches: [],
      activeRoomBindings: [],
      activeSupportRequests: [],
      activeEscalations: [],
      activeDecisionTickets: [],
      updatedAt: 2_500,
    };

    const state = runtimeStateFromAuthorityRuntimeSnapshot(snapshot);

    expect(state.primaryRequirementId).toBe("topic:mission:alpha");
    expect(state.activeRoomRecords[0]).toMatchObject({
      id: "workitem:topic:mission:alpha",
      workItemId: "topic:mission:alpha",
      topicKey: "mission:alpha",
      sessionKey: "room:workitem:topic:mission:alpha",
    });
    expect(state.activeMissionRecords[0]).toMatchObject({
      id: "topic:mission:alpha",
      topicKey: "mission:alpha",
      roomId: "workitem:topic:mission:alpha",
    });
    expect(state.activeWorkItems[0]).toMatchObject({
      id: "topic:mission:alpha",
      workKey: "topic:mission:alpha",
      topicKey: "mission:alpha",
      roomId: "workitem:topic:mission:alpha",
    });
    expect(state.activeRequirementAggregates[0]).toMatchObject({
      id: "topic:mission:alpha",
      topicKey: "mission:alpha",
      workItemId: "topic:mission:alpha",
      roomId: "workitem:topic:mission:alpha",
    });
    expect(state.activeConversationStates[0]).toMatchObject({
      currentWorkKey: "topic:mission:alpha",
      currentWorkItemId: "topic:mission:alpha",
      currentRoundId: "topic:mission:alpha@2000",
    });
    expect(state.activeRequirementEvidence[0]).toMatchObject({
      aggregateId: "topic:mission:alpha",
    });
    expect(state.activeRequirementEvidence[0]?.payload).toMatchObject({
      workItemId: "topic:mission:alpha",
      roomId: "workitem:topic:mission:alpha",
      topicKey: "mission:alpha",
    });
  });

  it("treats legacy decision rooms as waiting confirmation until a requirement decision ticket resolves", () => {
    const snapshot: AuthorityCompanyRuntimeSnapshot = {
      companyId: "company-1",
      activeRoomRecords: [
        {
          id: "workitem:topic:mission:alpha",
          companyId: "company-1",
          workItemId: "topic:mission:alpha",
          sessionKey: "room:workitem:topic:mission:alpha",
          title: "需求团队房间",
          topicKey: "mission:alpha",
          scope: "decision",
          memberIds: ["co-ceo", "co-cto", "co-coo"],
          memberActorIds: ["co-ceo", "co-cto", "co-coo"],
          ownerAgentId: "co-ceo",
          ownerActorId: "co-ceo",
          status: "active",
          transcript: [],
          createdAt: 1_000,
          updatedAt: 2_000,
        },
      ],
      activeMissionRecords: [],
      activeConversationStates: [],
      activeWorkItems: [
        {
          id: "topic:mission:alpha",
          workKey: "topic:mission:alpha",
          kind: "strategic",
          roundId: "topic:mission:alpha@1000",
          companyId: "company-1",
          sessionKey: "agent:co-ceo:main",
          topicKey: "mission:alpha",
          sourceActorId: "co-ceo",
          sourceActorLabel: "CEO",
          sourceSessionKey: "agent:co-ceo:main",
          sourceConversationId: "agent:co-ceo:main",
          providerId: null,
          title: "当前主线正在推进。",
          goal: "等待老板决策",
          headline: "当前主线正在推进。",
          displayStage: "团队回执已到齐",
          displaySummary: "24 条结论回传，等待 CEO 收口。",
          displayOwnerLabel: "CEO",
          displayNextAction: "CEO 收口并决定下一步。",
          status: "waiting_owner",
          lifecyclePhase: "active_requirement",
          stageGateStatus: "none",
          stageLabel: "团队回执已到齐",
          ownerActorId: "co-ceo",
          ownerLabel: "CEO",
          batonActorId: "co-ceo",
          batonLabel: "CEO",
          roomId: "workitem:topic:mission:alpha",
          artifactIds: [],
          dispatchIds: [],
          startedAt: 1_000,
          updatedAt: 2_500,
          completedAt: null,
          summary: "24 条结论回传，等待 CEO 收口。",
          nextAction: "CEO 收口并决定下一步。",
          steps: [],
        },
      ],
      activeRequirementAggregates: [
        {
          id: "topic:mission:alpha",
          companyId: "company-1",
          topicKey: "mission:alpha",
          kind: "strategic",
          primary: true,
          workItemId: "topic:mission:alpha",
          roomId: "workitem:topic:mission:alpha",
          ownerActorId: "co-ceo",
          ownerLabel: "CEO",
          lifecyclePhase: "active_requirement",
          stageGateStatus: "none",
          stage: "团队回执已到齐",
          summary: "24 条结论回传，等待 CEO 收口。",
          nextAction: "CEO 收口并决定下一步。",
          memberIds: ["co-ceo", "co-cto", "co-coo"],
          sourceConversationId: "agent:co-ceo:main",
          startedAt: 1_000,
          updatedAt: 2_500,
          revision: 1,
          lastEvidenceAt: null,
          status: "waiting_owner",
          acceptanceStatus: "not_requested",
          acceptanceNote: null,
        },
      ],
      activeRequirementEvidence: [],
      primaryRequirementId: "topic:mission:alpha",
      activeRoundRecords: [],
      activeArtifacts: [],
      activeDispatches: [],
      activeRoomBindings: [],
      activeSupportRequests: [],
      activeEscalations: [],
      activeDecisionTickets: [],
      updatedAt: 2_500,
    };

    const state = runtimeStateFromAuthorityRuntimeSnapshot(snapshot);

    expect(state.activeWorkItems[0]).toMatchObject({
      id: "topic:mission:alpha",
      lifecyclePhase: "pre_requirement",
      stageGateStatus: "waiting_confirmation",
    });
    expect(state.activeRequirementAggregates[0]).toMatchObject({
      id: "topic:mission:alpha",
      lifecyclePhase: "pre_requirement",
      stageGateStatus: "waiting_confirmation",
    });
  });
});
